// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2E_Yl3ceQ7NKSVvUiRfVj_8KNT5wjI98',
    appId: '1:301129261734:web:8a2c6cb1eb65e12b9e8a67',
    messagingSenderId: '301129261734',
    projectId: 'aquanav-8a6aa',
    authDomain: 'aquanav-8a6aa.firebaseapp.com',
    storageBucket: 'aquanav-8a6aa.firebasestorage.app',
    measurementId: 'G-5845D2PG8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwMJj9Gg7nwShBNmRTr8mcKGdD4qLSZak',
    appId: '1:301129261734:android:429319fcc45ef8209e8a67',
    messagingSenderId: '301129261734',
    projectId: 'aquanav-8a6aa',
    storageBucket: 'aquanav-8a6aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-esYZcZ6GqCgqWXm81qMFWh7rTXpmW8',
    appId: '1:301129261734:ios:9b169bc3f8464f649e8a67',
    messagingSenderId: '301129261734',
    projectId: 'aquanav-8a6aa',
    storageBucket: 'aquanav-8a6aa.firebasestorage.app',
    iosBundleId: 'com.example.aquanav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY-esYZcZ6GqCgqWXm81qMFWh7rTXpmW8',
    appId: '1:301129261734:ios:9b169bc3f8464f649e8a67',
    messagingSenderId: '301129261734',
    projectId: 'aquanav-8a6aa',
    storageBucket: 'aquanav-8a6aa.firebasestorage.app',
    iosBundleId: 'com.example.aquanav',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2E_Yl3ceQ7NKSVvUiRfVj_8KNT5wjI98',
    appId: '1:301129261734:web:744f9ee96cba7e559e8a67',
    messagingSenderId: '301129261734',
    projectId: 'aquanav-8a6aa',
    authDomain: 'aquanav-8a6aa.firebaseapp.com',
    storageBucket: 'aquanav-8a6aa.firebasestorage.app',
    measurementId: 'G-D1XN0XNVMP',
  );

}